---
- name: Install packages
  package:
    name:
      - "{{ item }}"
  with_items:
    - htop
    - tmux


- name: Create repo directory
  file:
    path: '/home/{{ USERNAME }}/repo/'
    state: directory
    mode: 0755
    recurse: yes