---
# Create Directories
- name: Create tools directory
  file:
    path: "/home/{{USERNAME}}/tools"
    owner: "{{USERNAME}}"
    group: "{{USERNAME}}"
    mode: '0750'
    state: directory

- name: Create windows tools directory
  file:
    path: "/home/{{USERNAME}}/tools/windows"
    owner: "{{USERNAME}}"
    group: "{{USERNAME}}"
    mode: '0750'
    state: directory

- name: Create linux tools directory
  file:
    path: "/home/{{USERNAME}}/tools/linux"
    owner: "{{USERNAME}}"
    group: "{{USERNAME}}"
    mode: '0750'
    state: directory

- name: Create linux tools directory
  file:
    path: "/home/{{USERNAME}}/tools/multi"
    owner: "{{USERNAME}}"
    group: "{{USERNAME}}"
    mode: '0750'
    state: directory

# Clone Repos

- name: Clone Linux repos
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/home/{{USERNAME}}/tools/linux/{{ item.name }}"
  with_items:
    - "{{ linux_privesc }}"

- name: Clone Windows repos
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/home/{{USERNAME}}/tools/windows/{{ item.name }}"
  with_items:
    - "{{ windows_privesc }}"

- name: Clone Multi repos
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/home/{{USERNAME}}/tools/multi/{{ item.name }}"
  with_items:
    - "{{ multi_privesc }}"
